modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "MPL-2.0"

[[mods]]
modId = "wagyourminimap-baritone"
version = "${version}"
displayName = "WagYourMinimap-Baritone"
authors = "Wagyourtail"
description = '''
Baritone integration for WagYourMinimap.
'''
#logoFile = ""

[[dependencies.wagyourminimap-baritone]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wagyourminimap-baritone]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wagyourminimap-baritone]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wagyourminimap-baritone]]
modId = "wagyourminimap"
mandatory = true
versionRange = "[1.0.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wagyourminimap-baritone]]
modId = "baritoe"
mandatory = true
versionRange = "[1.7.0,)"
ordering = "AFTER"
side = "BOTH"